### ISSUE TITLE
Mod3+- does not produce — (em dash)

### ISSUE THREAD

**Issue by tjanson** [jgosmann/Karabiner-Elements-Neo#4]
Mod3+- (Neo) / Mod3+ß (Qwertz labels) doesn’t do anything; it should produce an em dash: —

I tried adding it myself but did not succeed. Maybe I can help more if you tell me:

* How do I find out the `krbn::key_code` number of a key? They don’t seem related to [these Karabiner hex key codes](https://github.com/tekezo/Karabiner/blob/master/src/bridge/generator/keycode/data/KeyCode.data).
* I see the Layer 4 mappings in `src/core/grabber/include/manipulator/event_manipulator.hpp`, but where are Layer 3 mappings? Are they entirely in [`neo.keylayout`](http://wiki.neo-layout.org/browser/mac_osx/neo.keylayout?format=raw) and if so, why is this particular symbol missing?

**Comment by jgosmann** [comment]
Which keyboard layout file are you using? The one from http://neo-layout.org/? Or the one I provide in [jgosmann/neo2-layout-osx](https://github.com/jgosmann/neo2-layout-osx)? The problem is probably related to one of those files and potentially fixed in the version I provide (but maybe not).

> How do I find out the krbn::key_code number of a key? They don’t seem related to these Karabiner hex key codes.

Those are found in the [USB HID Usage Tables](http://www.usb.org/developers/hidpage/Hut1_12v2.pdf) starting at page 53.

> I see the Layer 4 mappings in src/core/grabber/include/manipulator/event_manipulator.hpp, but where are Layer 3 mappings? Are they entirely in neo.keylayout and if so, why is this particular symbol missing?

Yes, layer 3 mappings are entirely in the `neo.keylayout`. Interestingly, printable layer 4/6 symbols will invoke two key presses. The first is mapped as a dead key in `neo.keylayout` and the second key press then generates the symbol.

There were a few strange things in the `neo.keylayout`. That's why I did a bunch of changes to it, but I might have missed things.

**Comment by tjanson** [comment]
> Which keyboard layout file are you using? The one from http://neo-layout.org/?

Yes. I did just switch to yours temporarily, and it’s the same there. Also my shift key is now broken for most uppercase letters, so I’ll be switching back. ;)

I now noticed that the em dash is also present on layer 2 and works there, so this bug is definitely extremely low priority.

thanks for the additional information. maybe I’ll be able to contribute a bit.

**Comment by tjanson** [comment]
Actually I’ll assume that this is a bug/omission in the layout file and thus unrelated to the code here.

**Comment by jgosmann** [comment]
Both need to interact properly, so I would be fine with this issue here. I'm also fine with opening an issue at [jgosmann/neo2-layout-osx](https://github.com/jgosmann/neo2-layout-osx). Mainly I would like to haven an open issue for this somewhere as a reminder to investigate.

**Comment by jgosmann** [comment]
While there are certainly some graphics showing the em-dash on layer 3, others and especially the [reference in the Neo SVN](http://wiki.neo-layout.org/browser/A-REFERENZ-A/neo20.txt) list the mod3+- key as empty. As such I assume the current behaviour to be correct.

To type the em dash layer 2 is the intended way as you already noticed.
